### PR TITLE
Check that scheme-specific class inherits from URI

### LINKED ISSUE #50: URI->new() shouldn't create an URI::tel object
Hello!

I ran into a case where `URI->new()` behaves weirdly. If [URI::tel](https://metacpan.org/pod/URI::tel) (which doesn't inherit from URI) is installed, then it will build the wrong object:

```perl
my $uri = URI->new('tel:+16045551234');
print Dumper($uri);
print $uri->scheme();

__END__
OUTPUT:
$VAR1 = bless( {
                 'telephone_uri' => 'tel:tel:+16045551234'
               }, 'URI::tel' );
Can't locate object method "scheme" via package "URI::tel" at test.pl line 11.
```

The bug is really that URI::tel should be in a different namespace. But short of that, URI could probably check that any scheme-specific classes are subclasses before using them.

Cheers!

### PR DESCRIPTION
**Pull request by nfg**
Hello!

Here's a stab at #50. I wasn't sure what other tests should be added under tel.t, but this was enough to prove that the bug went away. Let me know if there's anything that should change.

Cheers!

Fixes #50

### CODE REVIEW

**Comment by oalders** [comment]
Hi Nigel,

Thanks so much for this!  Could you add a comment in the code that describes the specific problem that we're fixing?  I think that would be helpful for future reference.

**Comment by nfg** [comment]
Done! Is there anything else I can do?

**Comment by oalders** [comment]
Thanks!  I think we could specifically mention `URI::tel` in the comments just to be 100% clear what is going on.  Other than that, I'll just try to get one other person to review this before we merge.

**Comment by skaji** [comment]
FWIW this PR breaks https://metacpan.org/source/TBR/URI-tel-0.03/t/20-uri.t

**Comment by skaji** [comment]
And this also breaks https://metacpan.org/release/URI-db.

These examples shows that some modules depend on the current URI behavior,
so I think URI should keep the current behavior.

**Comment by nfg** [comment]
That's a good point. I'll file a ticket against URI::tel, because that's where I ran into this in the first place. Cheers!

**Pull request closed without merging**
