### PR TITLE
Convert to dzil.

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by karenetheridge** [comment]
I would strongly recommend, for the sake of installability and maintenance by different authors, to unroll the bundle into separate plugins. Dealing with the indirection of a bundle in a distribution under common maintenance often leads to headaches -- and some of the lwp distributions are special snowflakes that need special treatment in their configs.

**Comment by oalders** [comment]
Can this be solved with an `LWP` author bundle?  That would be an easy fix.  I put a decent amount of work into this and I'm not really inclined to rework all of the existing pull requests + other already completed dists with custom `dist.ini` files.  I don't think I have the time for it at the moment.

**Comment by karenetheridge** [comment]
> Can this be solved with an LWP author bundle?

Possibly -- although from when I glanced at it, it looked like libwww-perl was a *really* special snowflake :)

I can poke at it on the weekend, although I can't promise that my opinions will totally line up with yours :D

**Comment by oalders** [comment]
> I can poke at it on the weekend, although I can't promise that my opinions will totally line up with yours :D

Thanks!  I'm behind on my meta::hack prep and I need to get that set up for when we all get together next week.  I'm not attached to any of the logic in the bundle.  It's more the DRY that I'm interested in, if that's a workable solution.  If we just use it on modules that aren't bizarre, that's ok too.  Just trying to find a way to keep things sort of on the same page.

**Comment by oalders** [comment]
LGTM.  Maybe @karenetheridge could confirm that the `Makefile.PL` changes are ok.

**Comment by karenetheridge** [comment]
There doesn't seem to be any need for `[MakeMaker::Awesome]` here -- just `[MakeMaker]` should be fine.

**Pull request merged**
