### PR TITLE
Tidy import statements

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by vanHoesel** [comment]
It looks all clean to me, although I do wonder why you would desire to import variables and hashes. Or a technical explanation of why it is so important to not import anything. I'd try to refrain from 'cosmetic changes', as beautiful as they are.

All good to me though.

(once CHANGES gets updated obviously)

**Review by genio — APPROVED** [review]

**Comment by genio** [comment]
Please add a Changes comment or even a simple line with a `-` in it so that CheckChangesHasContent passes and we can tell if CI is passing. It might be best not to run author/release tests in CI

**Comment by genio** [comment]
@vanHoesel Being specific about what you import (only importing functions, etc. that are necessary) is good practice and not just a cosmetic change.

During compile time, anything imported from external packages gets put into your own package's namespace. Thus, telling the compiler _not_ to import anything helps keep your namespace clean and free of any collisions that might result in unexpected behavior. It makes it so you don't have to look up what each and every package exports by default every single time. If you know you aren't importing anything from them, then you're good.

Example:
If `Foo::Bar` exports a function `baz` by default and has function `bar` that isn't exported and `Bar::Foo` does exactly the same, then the following code would be confusing.

```perl
use Foo::Bar;
use Bar::Foo;

baz();
```

Whereas this code would not be confusing:

```perl
use Foo::Bar ();
use Bar::Foo qw(baz);

baz();
```

The reason for importing variables and hashes in some of these is because the tests use those variables/hashes. I agree that this is not really pretty to do, but it's again for the purpose of being explicit.

**Comment by oalders** [comment]
Thanks for the reviews!

> Please add a Changes comment or even a simple line with a - in it so that CheckChangesHasContent passes and we can tell if CI is passing.

I've done that and force-pushed.

> It might be best not to run author/release tests in CI

I'll likely switch this over to GitHub workflows and set it up so that author tests don't hold up the rest of the builds. I'd still want to catch things like missing Pod etc, but it's painful to see CI grind to a halt over a missing Changes entry.

**Comment by oalders** [comment]
@vanHoesel in addition to @genio's very helpful answer on the motivation for making exports explicit, I've written up a document here: https://github.com/oalders/App-perlimports#motivation

**Comment by petdance** [comment]
This makes me happy. 👍

**Comment by oalders** [comment]
Thanks, @petdance! I actually thought this might get a fair amount of pushback. 😄

**Comment by karenetheridge** [comment]
Author tests should continue to run in CI -- these are tests that should pass after every commit.

If you don't want to check Changes entries as part of author testing, that can easily be changed in dist.ini.

**Comment by oalders** [comment]
> If you don't want to check Changes entries as part of author testing, that can easily be changed in dist.ini.

Cool. I run a script to generate the changes for each release anyway, so I'm not personally too concerned with having that file updated as part of a PR.

**Pull request merged**
