### PR TITLE
use URI implicitly in URI::QueryParam

### PR DESCRIPTION
**Pull request by Grinnz**
Saves some typing, and this module is useless if URI is not loaded anyway.

### CODE REVIEW

**Comment by karenetheridge** [comment]
Yes, but...
how much typing will it save if you need to guarantee you've got the latest URI installed? I fear that once code is written that takes advantage of this, there's going to be a bunch of "argh URI didn't get loaded" errors popping up in other places. :/

**Comment by Grinnz** [comment]
Maybe if it's documented that "use URI" is needed before that version? or in the synopsis as "use URI::QueryParam x.xx"?

**Comment by oalders** [comment]
I think this makes sense.  Having to use `URI` explicitly in order to be able to use this module is a bit weird.

**Comment by Grinnz** [comment]
The other option is to just roll the queryparam functions into URI::query, since 4 more methods is not a whole lot of difference.

**Comment by oalders** [comment]
That would be a much nicer solution.  I wonder what the back story is here.  Does anyone know why QueryParam.pm exists on its own?

**Comment by haarg** [comment]
I would say if we want to change anything here, it should be to fold the functions directly into URI and make URI::QueryParam a no-op.

**Comment by oalders** [comment]
Closed via #114. Thanks, @Grinnz!

**Pull request closed without merging**
