### PR TITLE
URI::_punycode - Privatize functions

### PR DESCRIPTION
**Pull request by genio**
Update URI::_punycode to make several functions that have never
been documented and have always been considered private to
actually be private.

* adapt -> _adapt
* code_point -> _code_point
* digit_value ->  _digit_value
* min -> _min

This allows us to remove some special casing in the dist.ini conf
file, reducing complexity.

### CODE REVIEW

**Comment by karenetheridge** [comment]
let's confirm via grep.cpan.me that this doesn't impact any cpan modules...

**Comment by oalders** [comment]
@genio were you able to grep CPAN for any issues?

**Comment by genio** [comment]
I'm not quite sure anymore. I kind of remember spending a few minutes thinking of how to search for any use of these functions using grep.cpan.me, but I didn't come up with anything and moved on.

**Review by simbabque — APPROVED** [review]

**Comment by simbabque** [comment]
@haarg did a grep just now. Nothing uses URI::_punycode as far as we can see. Should be fine to merge.

**Comment by simbabque** [comment]
Thank you @genio.

**Pull request merged**
