### PR TITLE
Add scp, ftps, ftpes, irc, ircs schemes

### PR DESCRIPTION
**Pull request by SineSwiper**
Added several schemes that were simple to implement, as they were aliases or mostly aliases to existing types.  I also added the irc scheme, based on existing IRC URI drafts, and its secure cousin, ircs.

URI::sftp is already out there in the wild, but it would be nice to bring this thing into the core URI distro.

### CODE REVIEW

**Comment by oalders** [comment]
It looks like we're now shipping `URI::sftp` with `URI`. @SineSwiper do you still have interest in getting some of this merged? I have no idea why it got stalled.

**Comment by SineSwiper** [comment]
@oalders, @karenetheridge Apologies for the (very late) delay, but I noticed there was still an interest in getting this merged.  So, I rebased it and cleaned it up to match the newer URI fixes (Test::More, DZIL, etc.).

**Comment by oalders** [comment]
@SineSwiper sorry for the delay in review. What do you think about adding some basic tests for the new modules which don't yet have coverage?

**Comment by SineSwiper** [comment]
@oalders, there should be some unit tests for the new modules in the commits.  Did you find any modules missing tests?

**Comment by oalders** [comment]
@SineSwiper I see what you mean now. At first glance I saw new modules, but I didn't see corresponding test files for each. 

If it's not too much trouble, could we put the `ircs` and `ftpes` tests into their own `.t` files? I think that makes it easier to get a quick overview of things.

Maybe if we added a compile test or something basic for `scp` as well? I don't see anything for that.

**Comment by SineSwiper** [comment]
Okay, I split up the tests, added some new ones, and rebased to fix the `$VERSION` mismatches.

**Comment by oalders** [comment]
It took an entire decade, but we got there. 😅 Sorry for the delay @SineSwiper (I think this predates me?) and thank you for your patience.

**Comment by oalders** [comment]
Oof. I should have checked first:

>  Status: Permission missing
> ==========================
> 
>      module : URI::ftpes
>      version: 5.30
>      in file: lib/URI/ftpes.pm
>      status : Not indexed because permission missing. Current registered
>               primary maintainer is STEFANOS. Hint: you can always find
>               the legitimate maintainer(s) on PAUSE under "View
>               Permissions".
> 
>      module : URI::ftps
>      version: 5.30
>      in file: lib/URI/ftps.pm
>      status : Not indexed because permission missing. Current registered
>               primary maintainer is STEFANOS. Hint: you can always find
>               the legitimate maintainer(s) on PAUSE under "View
>               Permissions".
> 
>      module : URI::scp
>      version: 5.30
>      in file: lib/URI/scp.pm
>      status : Not indexed because permission missing. Current registered
>               primary maintainer is STEFANOS. Hint: you can always find
>               the legitimate maintainer(s) on PAUSE under "View
>               Permissions".

**Comment by oalders** [comment]
It looks like those are actually just on BackPAN. I'll contact a PAUSE admin about transferring perms.

**Comment by SineSwiper** [comment]
No worries!  Thanks for getting it merged!

**Pull request merged**
