### PR TITLE
Reorganize directory structure.

### PR DESCRIPTION
**Pull request by adamherzog**
Move modules into lib/, script into bin/, and update Makefile.PL/MANIFEST with new paths.

(This had been submitted in #9, but it was closed before ever being applied.)

### CODE REVIEW

**Comment by karenetheridge** [comment]
This is good, except uri-test should stay where it is, as it is not intended to be installed for users. (If it were, it would have documentation, and be mentioned as an installable executable in EXE_FILES in Makefile.PL.)

**Comment by adamherzog** [comment]
Thanks, @karenetheridge. I've moved uri-test back to its original location.

**Comment by karenetheridge** [comment]
Super!  Could you possibly squash those commits into one and force-push your branch?

**Comment by adamherzog** [comment]
Oh! I should've thought of that. :) Squashed and pushed.

**Comment by karenetheridge** [comment]
thank you very much!

**Comment by karenetheridge** [comment]
1.66 has been released. Thanks again!

**Pull request merged**
