### PR TITLE
Merge pull requests 10, 17 and 18

### PR DESCRIPTION
**Pull request by oalders**
I took the liberty of merging and testing pulls #10, #17 and #18.  Mostly I'm interested in #18, but the others seem pretty straightforward as well.  #18 had a merge conflict.  I could pare this down to just #18 if that's desirable, since there are no actual merge commits here.

Test results for the code changes are here: http://matrix.cpantesters.org/?dist=URI+1.67_01

The CPAN upload is at https://metacpan.org/release/OALDERS/URI-1.67_01 but doesn't contain the Changes file.

### CODE REVIEW

**Comment by karenetheridge** [comment]
Thanks, I'll process this tonight!

**Comment by oalders** [comment]
:+1:

**Comment by karenetheridge** [comment]
Thanks, merged!

**Comment by oalders** [comment]
:cake:

**Pull request closed without merging**
