### PR TITLE
Adding otpauth URI

### PR DESCRIPTION
**Pull request by david-dick**
Can we add the URI::otpauth type?  It means we would need to add MIME::Base32 as a dependency.

### CODE REVIEW

**Review by oalders — APPROVED** [review]
Thanks! This looks good to me. I'll wait a few days before merging to see if anyone else wants to offer an opinion.

**Comment by hightowe** [comment]
@oalders - I think that this feature added a regression, reported to me today by a kpcli user, as follows:

> Le Thu, May 08, 2025 at 09:01:15AM +0200, Landry Breuil a écrit :
> [...snip...]
> > with 4.1.2 & the URI module 5.28, the otp feature worked fine
> >
> > with URI 5.31 (and i guess since 5.29 which has
> > https://github.com/libwww-perl/URI/pull/145) the otp feature fails here,
> > eg when showing an entry that has an otpauth url, i get this:
> >
> > Can't locate object method "authority" via package "URI::otpauth" at
> > /usr/local/bin/kpcli line 8662.
> >
> > i guess this is related to the above PR..
> 
> after looking, it seems replacing $uri->authority by $uri->type achieves
> the same feature (eg the 'totp' part of the url) and makes the otp
> feature work again.
> 
> but since in the upstream PR the otpauth subclass claims that it
> supports the generic/common methods:
> 
> `URI` objects belonging to the otpauth scheme support the common methods.
> 
> so afaict it should still support the 'authority' method. so i'm puzzled
> if that's a bug in the above PR and something to fix/report there, or to
> work around in kpcli.
> 
> Landry

I believe that Landry is correct that the 'authority' method should still be supported by this change and it is not, and thus it created an unintended regression. Would you mind looking it over and, if you agree, adding that missing method?

Thanks,
Lester

**Comment by oalders** [comment]
Thanks for this report, @hightowe! @david-dick are you able to take a look at this?

**Comment by hightowe** [comment]
> Thanks for this report, @hightowe! @david-dick are you able to take a look at this?

In case it is helpful, this is the line of code in kpcli 4.1.2 that triggers the problem reported here: https://sourceforge.net/p/kpcli/code/HEAD/tree/releases/4.x/kpcli-4.1.2.pl#l8664 

The missing authority method is the issue...

**Comment by hightowe** [comment]
I opened an issue on this and Landry put a small script there that reproduces the problem: https://github.com/libwww-perl/URI/issues/152

**Pull request merged**
